using System.Collections.Generic;


namespace EREnemyOnslaught
{
    internal static class Models
    {
        public readonly static Dictionary<string, string> CharacterModels = new Dictionary<string, string>()
        {
            ["c0000"] = "Human NPC/Player",
            ["c0100"] = "Unknown (c0100)",
            ["c0110"] = "Unknown (c0110)",
            ["c0120"] = "Unknown (c0120)",
            ["c0130"] = "Unknown (c0130)",
            ["c1000"] = "Empty (c1000)",
            ["c2010"] = "Blaidd",
            ["c2030"] = "Rennala",
            ["c2031"] = "Rennala",
            ["c2040"] = "Rennala Student",
            ["c2041"] = "Rennala Student",
            ["c2050"] = "Ranni",
            ["c2060"] = "The Two Fingers",
            ["c2070"] = "The Three Fingers",
            ["c2100"] = "Black Knife Assassin/Alecto, Black Knife Ringleader",
            ["c2110"] = "Beast Clergyman/Maliketh",
            ["c2120"] = "Malenia, Blade of Miquella",
            ["c2130"] = "Morgott/Margit",
            ["c2131"] = "Morgott (Defeated)",
            ["c2140"] = "Fell Twins",
            ["c2150"] = "Wisp",
            ["c2160"] = "Finger Reader Crone",
            ["c2170"] = "Finger Reader Enia",
            ["c2180"] = "Melina",
            ["c2190"] = "Radagon",
            ["c2200"] = "Elden Beast",
            ["c2270"] = "Large Crab",
            ["c2271"] = "Small Crab",
            ["c2272"] = "Large Crab",
            ["c2273"] = "Small Crab",
            ["c2274"] = "Large Crab",
            ["c2275"] = "Small Crab",
            ["c2276"] = "Small Crab",
            ["c2277"] = "Small Crab",
            ["c2500"] = "Crucible Knight",
            ["c3000"] = "Exile Soldier",
            ["c3010"] = "Banished Knight",
            ["c3020"] = "Exile Soldier",
            ["c3050"] = "Commander Niall",
            ["c3060"] = "Undead Mariner",
            ["c3061"] = "Undead Azula Beastman",
            ["c3070"] = "Dominula Celebrant",
            ["c3080"] = "Imp",
            ["c3100"] = "Bell Bearing Hunter / Elemer of the Briar",
            ["c3150"] = "Night's Calvary",
            ["c3160"] = "Night's Calvary Horse",
            ["c3170"] = "Albinauric Archer",
            ["c3171"] = "Albinauric Archer",
            ["c3180"] = "Wolf",
            ["c3181"] = "Red Wolf of Radagon",
            ["c3200"] = "Nomad Trader",
            ["c3201"] = "Nomad Trader",
            ["c3210"] = "Nomad Mule",
            ["c3250"] = "Draconic Tree Sentinel",
            ["c3251"] = "Tree Sentinel",
            ["c3252"] = "Royal Knight Loretta",
            ["c3300"] = "Nox Swordstress/Nox Priest",
            ["c3320"] = "Silver Tear",
            ["c3330"] = "Silver Tear Orb",
            ["c3350"] = "Crystalian",
            ["c3360"] = "Ancestral Follower",
            ["c3361"] = "Ancestral Follower",
            ["c3370"] = "Ancestral Follower Shaman",
            ["c3371"] = "Ancestral Follower Shaman",
            ["c3400"] = "Grave Warden Duelist",
            ["c3450"] = "Misbegotten",
            ["c3451"] = "Misbegotten / Hewg",
            ["c3460"] = "Leonine Misbegotten",
            ["c3470"] = "Albinauric",
            ["c3471"] = "Albinauric",
            ["c3500"] = "Skeleton",
            ["c3510"] = "Skeleton",
            ["c3550"] = "Sanguine Noble",
            ["c3560"] = "Godskin Apostle",
            ["c3570"] = "Godskin Noble",
            ["c3600"] = "Onyx/Alabaster Lord",
            ["c3610"] = "Oracle Envoy",
            ["c3620"] = "Oracle Envoy",
            ["c3630"] = "Oracle Envoy",
            ["c3650"] = "Erdtree Guardian",
            ["c3660"] = "Commoner",
            ["c3661"] = "Putrid Corpse",
            ["c3662"] = "Putrid Corpse",
            ["c3664"] = "Cemetery Shade",
            ["c3665"] = "Devious Commoner / Gostoc",
            ["c3666"] = "Sunflower Commoner / Goldmask",
            ["c3670"] = "Albinauric Lookout",
            ["c3700"] = "Perfumer Tricia",
            ["c3701"] = "Depraved Perfumer",
            ["c3702"] = "Raya Lucaria Scholar",
            ["c3703"] = "Noble's Page",
            ["c3704"] = "Battle Mage Hughes",
            ["c3710"] = "Crystallized Battlemage",
            ["c3720"] = "Orbhead Sorcerer",
            ["c3730"] = "Arcane Sphere of Faces",
            ["c3750"] = "Clayman",
            ["c3800"] = "Cleanrot Knight",
            ["c3810"] = "Kindred of Rot",
            ["c3850"] = "Marionette",
            ["c3860"] = "Avionette",
            ["c3900"] = "Fire Monk",
            ["c3901"] = "Godskin Monk",
            ["c3910"] = "Fire Prelate",
            ["c3950"] = "Man-Serpent",
            ["c3970"] = "Beastman of Farum Azula",
            ["c4000"] = "Royal Rider",
            ["c4020"] = "Royal Revenant",
            ["c4040"] = "Sewer Slug",
            ["c4050"] = "Kaiden Sellsword",
            ["c4060"] = "Kaiden Sellsword Horse",
            ["c4070"] = "Wolf",
            ["c4071"] = "Wolf",
            ["c4080"] = "Rat",
            ["c4090"] = "Giant Rat",
            ["c4100"] = "Demi-Human",
            ["c4101"] = "Large Demi-Human",
            ["c4110"] = "Demi-Human Shaman",
            ["c4120"] = "Demi-Human Chief",
            ["c4130"] = "Demi-Human Queen",
            ["c4140"] = "Spirit Caller Snail",
            ["c4150"] = "Basilisk",
            ["c4160"] = "Larger Dog",
            ["c4161"] = "Larger Dog",
            ["c4162"] = "Starved Dog",
            ["c4163"] = "Starved Dog",
            ["c4164"] = "Larger Dog With Less Hair",
            ["c4165"] = "Larger Dog With Less Hair",
            ["c4166"] = "Starved Dog",
            ["c4167"] = "Starved Dog",
            ["c4170"] = "Living Mass",
            ["c4171"] = "Living Mass",
            ["c4180"] = "Spirit Jellyfish",
            ["c4190"] = "Scarab",
            ["c4191"] = "Scarab",
            ["c4192"] = "Scarab",
            ["c4200"] = "Giant Bat",
            ["c4201"] = "Chanting Winged Dame",
            ["c4210"] = "Bladed Talon Eagle",
            ["c4220"] = "Giant Octopus",
            ["c4230"] = "Octopus",
            ["c4240"] = "Fingercreeper/Spider Hand",
            ["c4241"] = "Large Fingercreeper/Spider Hand",
            ["c4250"] = "Lesser Fingercreeper/Spider Hand",
            ["c4260"] = "Erdtree Burial Watchdog",
            ["c4270"] = "Lion Guardian",
            ["c4280"] = "Giant Ant",
            ["c4281"] = "Giant Ant - Sac",
            ["c4290"] = "Bloodhound Knight",
            ["c4300"] = "Wandering Noble",
            ["c4310"] = "Soldier",
            ["c4311"] = "Godrick Soldier",
            ["c4312"] = "Raya Lucaria Soldier",
            ["c4313"] = "Leyndell Soldier",
            ["c4314"] = "Radahn Soldier",
            ["c4315"] = "Mausoleum Soldier",
            ["c4316"] = "Haligtree Soldier",
            ["c4320"] = "Vulgar Militia",
            ["c4321"] = "Vulgar Militia",
            ["c4340"] = "Mad Pumpkin Head",
            ["c4341"] = "Lesser Pumpkin Head",
            ["c4350"] = "Castle Knight",
            ["c4351"] = "Godrick Knight",
            ["c4352"] = "Cuckoo Knight",
            ["c4353"] = "Leyndell Knight",
            ["c4354"] = "Redmane Knight",
            ["c4355"] = "Mausoleum Knight",
            ["c4356"] = "Haligtree Knight",
            ["c4360"] = "Knight's Horse",
            ["c4361"] = "Godrick Knight's Horse",
            ["c4362"] = "Cuckoo Knight's Horse",
            ["c4363"] = "Leyndell Knight's Horse",
            ["c4364"] = "Redmane Knight's Horse",
            ["c4365"] = "Mausoleum Knight's Horse",
            ["c4366"] = "Haligtree Knight's Horse",
            ["c4370"] = "Foot Soldier",
            ["c4371"] = "Godrick Foot Soldier",
            ["c4372"] = "Raya Lucaria Foot Soldier",
            ["c4373"] = "Leyndell Foot Soldier",
            ["c4374"] = "Radahn Foot Soldier",
            ["c4375"] = "Mausoleum Foot Soldier",
            ["c4376"] = "Haligtree Foot Soldier",
            ["c4377"] = "Highwayman",
            ["c4380"] = "Starcaller",
            ["c4381"] = "Bloodthorn Exile",
            ["c4382"] = "Tunnel Miner",
            ["c4383"] = "Glintstone Miner",
            ["c4384"] = "Glintstone Miner",
            ["c4385"] = "Fungal Sorcerer",
            ["c4420"] = "Giant Lobster",
            ["c4430"] = "Abnormal Stone Cluster",
            ["c4440"] = "Fungal Pod",
            ["c4441"] = "Giant Fungal Pod",
            ["c4442"] = "Giant Rotten Pod",
            ["c4450"] = "Walking Mausoleum",
            ["c4460"] = "Maneuverable Flamethrower",
            ["c4470"] = "Abductor Virgin",
            ["c4480"] = "Miranda the Blighted Bloom/Blossom",
            ["c4481"] = "Miranda Sprout",
            ["c4482"] = "Giant Miranda Sprout",
            ["c4483"] = "Miranda Sprout",
            ["c4490"] = "Living Pot",
            ["c4491"] = "Living Pot",
            ["c4492"] = "Living Pot",
            ["c4500"] = "Flying Dragon Agheel/Greyll",
            ["c4501"] = "Flying Dragon Agheel/Greyll",
            ["c4502"] = "Glintstone Dragon Smarag/Adula",
            ["c4503"] = "Borealis the Freezing Fog",
            ["c4504"] = "Elder Dragon Greyoll",
            ["c4505"] = "Lesser Dragon",
            ["c4510"] = "Ancient Dragon Lansseax",
            ["c4511"] = "Lichdragon Fortissax",
            ["c4520"] = "Dragonlord Placidusax",
            ["c4550"] = "Monstrous Dog",
            ["c4560"] = "Monstrous Crow",
            ["c4561"] = "Monstrous Crow",
            ["c4570"] = "Wormface",
            ["c4580"] = "Wormface",
            ["c4600"] = "Stonedigger Troll/Bols, Carian Knight",
            ["c4601"] = "Armored Troll Knight",
            ["c4602"] = "Troll Knight",
            ["c4603"] = "Smithing Master Iji",
            ["c4604"] = "War Counselor Iji",
            ["c4620"] = "Astel, Naturalborn of the Void",
            ["c4630"] = "Runebear",
            ["c4640"] = "Ulcerated/Putrid Tree Spirit",
            ["c4650"] = "Dragonkin Soldier of Nokstella",
            ["c4660"] = "Guardian Golem",
            ["c4670"] = "Ancestor Spirit",
            ["c4680"] = "Fallingstar Beast",
            ["c4690"] = "Grafted Scion",
            ["c4710"] = "God-Devouring Serpent / Rykard",
            ["c4711"] = "Writhing Mass",
            ["c4720"] = "Godfrey, The First Elden Lord",
            ["c4721"] = "Hoarah Loux the Warrior",
            ["c4730"] = "Starscourge Radahn",
            ["c4750"] = "Godrick the Grafted",
            ["c4751"] = "Godrick the Grafted (Defeated)",
            ["c4760"] = "Fire Giant",
            ["c4770"] = "Black Blade Kindred",
            ["c4800"] = "Mohg, The Omen",
            ["c4810"] = "Erdtree Avatar",
            ["c4811"] = "Putrid Avatar",
            ["c4820"] = "Omenkiller",
            ["c4910"] = "Magma Wyrm",
            ["c4911"] = "Great Wyrm Theodorix",
            ["c4950"] = "Tibia Mariner",
            ["c4960"] = "Giant Skeleton Torso",
            ["c4980"] = "Death Rite Bird",
            ["c6000"] = "Eagle",
            ["c6001"] = "Eagle",
            ["c6010"] = "Deer",
            ["c6030"] = "Bear",
            ["c6031"] = "Bear",
            ["c6040"] = "Owl",
            ["c6050"] = "Boar",
            ["c6060"] = "Wild Mouflon",
            ["c6070"] = "Guillemot",
            ["c6071"] = "Guillemot",
            ["c6072"] = "Carrier Pidgeon",
            ["c6080"] = "Giant Dragonfly",
            ["c6081"] = "Giant Dragonfly",
            ["c6082"] = "Giant Dragonfly",
            ["c6090"] = "Turtle",
            ["c6091"] = "Giant Turtle / Miriel Pastor of Vows",
            ["c6100"] = "Rabbitgaroo",
            ["c7000"] = "Fallen Hawks Soldier",
            ["c7100"] = "Ancient Hero of Zamor",
            ["c8000"] = "Torrent",
            ["c8100"] = "Ballista",
            ["c8101"] = "Giant Ballista",
            ["c8110"] = "Dragon-Faced Flamethrower",
            ["c8120"] = "Merciless Chariot",
            ["c8900"] = "Malenia, Blade of Miquella",
            ["c8901"] = "Beast Clergyman/Maliketh, the Black Blade",
            ["c8903"] = "Rennala",
            ["c8904"] = "Morgott",
            ["c8905"] = "Mohg, Lord of Blood",
            ["c8906"] = "Melina",
            ["c8907"] = "Malformed Ranni",
            ["c9001"] = "TextSphere",
        };

        public readonly static List<string> IgnoreModels = new List<string>()
        {
            //"Human NPC/Player",
            "Melina",  // just in case
            "Unknown (c0100)",
            "Unknown (c0110)",
            "Unknown (c0120)",
            "Unknown (c0130)",
            "Empty (c1000)",
            "Torrent",
            "TextSphere",
            "Merciless Chariot",
        };

        public readonly static List<string> BossModels = new List<string>()
        {
            // Very rough, and obviously some models appear as both bosses and non-bosses.
            "Rennala",
            "Rennala",
            "Black Knife Assassin/Alecto, Black Knife Ringleader",
            "Beast Clergyman/Maliketh",
            "Malenia, Blade of Miquella",
            "Morgott/Margit",
            "Radagon",
            "Elden Beast",
            "Commander Niall",
            "Bell Bearing Hunter / Elemer of the Briar",
            "Night's Calvary",
            "Night's Calvary Horse",
            "Red Wolf of Radagon",
            "Draconic Tree Sentinel",
            "Tree Sentinel",
            "Royal Knight Loretta",
            "Godskin Apostle",
            "Godskin Noble",
            "Onyx/Alabaster Lord",
            "Perfumer Tricia",
            "Beastman of Farum Azula",
            "Demi-Human Queen",
            "Miranda the Blighted Bloom/Blossom",
            "Flying Dragon Agheel/Greyll",
            "Flying Dragon Agheel/Greyll",
            "Glintstone Dragon Smarag/Adula",
            "Borealis the Freezing Fog",
            "Ancient Dragon Lansseax",
            "Lichdragon Fortissax",
            "Dragonlord Placidusax",
            "Astel, Naturalborn of the Void",
            "Ulcerated/Putrid Tree Spirit",
            "Dragonkin Soldier of Nokstella",
            "Guardian Golem",
            "Ancestor Spirit",
            "Fallingstar Beast",
            "Grafted Scion",
            "God-Devouring Serpent / Rykard",
            "Writhing Mass",
            "Godfrey, The First Elden Lord",
            "Hoarah Loux the Warrior",
            "Starscourge Radahn",
            "Godrick the Grafted",
            "Fire Giant",
            "Black Blade Kindred",
            "Mohg, The Omen",
            "Erdtree Avatar",
            "Putrid Avatar",
            "Magma Wyrm",
            "Great Wyrm Theodorix",
            "Tibia Mariner",
            "Death Rite Bird",
            "Fallen Hawks Soldier",
            "Ancient Hero of Zamor",
            "Malenia, Blade of Miquella",
            "Beast Clergyman/Maliketh, the Black Blade",
            "Rennala",
            "Morgott",
            "Mohg, Lord of Blood",
        };
    }
}
